version: '3.8'
services:
  gateway:
    env_file:
      - ./back-end/services/gateway/.env.docker
    build:
      context: ./back-end
      dockerfile: ./services/gateway/Dockerfile.dev
    volumes:
      - ./back-end/services/gateway/:/src/app
    ports:
      - 4001:4001
      - 2347:2345
    depends_on:
      - redis
  frontend:
    env_file:
      - ./front-end/marketplace/.env.docker
    build:
      context: ./front-end/marketplace
      dockerfile: Dockerfile.dev
    volumes:
      - ./front-end/marketplace/:/src/app
    ports:
      - 3500:3000
  catalog:
    env_file:
      - ./back-end/services/catalog/.env.docker
    build:
      context: ./back-end
      dockerfile: ./services/catalog/Dockerfile.dev
    volumes:
      - ./back-end/services/catalog/:/src/app
    ports:
      - 4002:4002
      - 2346:2345
  authentication:
    env_file:
      - ./back-end/services/authentication/.env.docker
    build:
      context: ./back-end
      dockerfile: ./services/authentication/Dockerfile.dev
    volumes:
      - ./back-end/services/authentication/:/src/app
    ports:
      - 4003:4003
      - 2348:2345
    depends_on:
      - mongodb
      - nats
  analytics:
    env_file:
    - ./back-end/services/analytics/.env.docker
    build:
      context: ./back-end
      dockerfile: ./services/analytics/Dockerfile.dev
    volumes:
      - ./back-end/services/analytics/:/src/app:rw,delegated
    ports:
      - 4004:4004
      - 2349:2345
    depends_on:
      - nats
      - postgres
  customer:
    env_file:
    - ./back-end/services/customer/.env.docker
    build:
      context: ./back-end
      dockerfile: ./services/customer/Dockerfile.dev
    volumes:
      - ./back-end/services/customer/:/src/app:rw,delegated
    ports:
      - 4006:4006
      - 2350:2345
    depends_on:
      - nats
      - postgres
  cart:
    env_file:
    - ./back-end/services/cart/.env.docker
    build:
      context: ./back-end
      dockerfile: ./services/cart/Dockerfile.dev
    volumes:
      - ./back-end/services/cart/:/src/app:rw,delegated
    ports:
      - 4007:4007
      - 2351:2345
    depends_on:
      - nats
      - postgres
  notification:
    env_file:
    - ./back-end/services/notification/.env.docker
    build:
      context: ./back-end
      dockerfile: ./services/notification/Dockerfile.dev
    volumes:
      - ./back-end/services/notification/:/src/app:rw,delegated
    ports:
      - 4005:4005
    depends_on:
      - nats
      - postgres
  chat:
    env_file:
    - ./back-end/services/chat/.env.docker
    build:
      context: ./back-end/services/chat
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./back-end/services/chat/src:/src/app/src:rw,delegated
    ports:
      - 4008:3000
      - 4009:80
    depends_on:
      - nats
      - postgres
  nats:
    image: nats:latest
    entrypoint: ["/nats-server", "-js"]
    ports:
    - "4222:4222"
    - "8222:8222"
    - "6222:6222"
    restart: always
    tty: true
  mongodb:
    container_name: marketplace-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/marketplace/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: db    
  postgres:
    container_name: marketplace_postgres_container
    image: postgres
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/marketplace/postgres
    volumes:
       - postgres:/data/marketplace/postgres
    ports:
      - "5437:5432"
    restart: unless-stopped
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
    - "4333:8080"
    environment:
      SWAGGER_JSON: /tmp/open-api.yaml
    volumes:
      - ./back-end:/tmp:rw,delegated
    restart: always
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
    - "4444:8080"
    environment:
      SWAGGER_FILE: /tmp/open-api.yaml
    volumes:
      - ./back-end:/tmp:rw,delegated
    restart: always
  redis:
    container_name: marketplace_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/marketplace/data
    command: redis-server --appendonly yes
volumes:
  postgres:
  redis-data:
  mongodbdata:
