app:
  name: gateway-service
  version: '0.0.1'
frontend_url: ${FRONTEND_URL}
catalog_service_url: ${CATALOG_SERVICE_URL}
redis_address: ${REDIS_ADDRESS}
authentication_service_url: ${AUTHENTICATION_SERVICE_URL}
swagger_ui_domain: ${SWAGGER_UI_DOMAIN}
swagger_editor_domain: ${SWAGGER_EDITOR_DOMAIN}
http:
  port: ${PORT}