app:
  name: gateway
  version: '0.0.1'
marketplace_app_url: ${MARKETPLACE_APP_URL}
accounts_app_url: ${ACCOUNTS_APP_URL}
catalog_service_url: ${CATALOG_SERVICE_URL}
cart_service_url: ${CART_SERVICE_URL}
chat_service_websocket_url: ${CHAT_SERVICE_WEBSOCKET_URL}
chat_service_url: ${CHAT_SERVICE_URL}
redis_address: ${REDIS_ADDRESS}
authentication_service_url: ${AUTHENTICATION_SERVICE_URL}
notification_service_url: ${NOTIFICATION_SERVICE_URL}
swagger_ui_domain: ${SWAGGER_UI_DOMAIN}
swagger_editor_domain: ${SWAGGER_EDITOR_DOMAIN}
http:
  port: ${PORT}
