openapi: 3.0.3
info:
  title: Marketplace - OpenAPI 3.0
  description: >-
    Sample Marketplace 
  version: 1.0.0
servers:
  - url: http://localhost:4001/v1
tags:
  - name: product
    description: Operations about product
paths:
  /products:
    post:
      tags:
        - product
      summary: Creates product
      operationId: createProduct
      requestBody:
        description: Creates a product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreationInput'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponseSuccess'
    get:
      tags:
        - product
      summary: Feches a product list
      operationId: fetchProductList
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
  /products/:productId:
    get:
      tags:
        - product
      summary: Fetches a product
      operationId: fetchProduct
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
components:
  schemas:
    ProductCreationInput:
      type: object
      properties:
        name:
          type: string
          example: Banana
        price:
          type: number
          example: 2.55
        quantity:
          type: integer
          example: 2
    Product:
      type: object
      properties:
        type:
          type: string
        id:
          type: string
        name:
          type: string
          example: Banana
        price:
          type: number
          example: 2.55
        quantity:
          type: integer
          example: 2
    ProductList:
      type: object
      properties:
        type:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    ApiResponseError:
      type: object
      properties:
        message:
          type: string
        success:
          type: boolean
          example: false    
    ApiResponseSuccess:
      type: object
      properties:
        message:
          type: string
        success:
          type: boolean
          example: true
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: header
      name: session 
security:
  - cookieAuth: []
