app:
  name: 'authentication'
  version: '0.0.1'
frontend_url: ${FRONTEND_URL}
project_root: ${PROJECT_ROOT}
gateway_url: ${GATEWAY_URL}
http:
  port: ${PORT}
session_secret: ${SESSION_SECRET}
social_sign_in:
  github_key: ${GITHUB_KEY}
  github_secret: ${GITHUB_SECRET}
  google_key: ${GOOGLE_KEY}
  google_secret: ${GOOGLE_SECRET}
nats_uri: ${NATS_URI}
mongo_url: ${MONGO_URI}
mongo_database_name: ${MONGO_DATABASE_NAME}
