FROM golang:1.20.5-alpine

RUN apk add --no-cache git

WORKDIR /

COPY /pkg pkg

WORKDIR /src/app

COPY /services/authentication-service/go.mod .
COPY /services/authentication-service/go.sum .

RUN go mod download
RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY /services/authentication-service .

CMD ["air",  "-c", ".air_debug.toml"]

