app:
  name: 'catalog'
  version: '0.0.1'
project_root: ${PROJECT_ROOT}
swagger_ui_domain: ${SWAGGER_UI_DOMAIN}
swagger_editor_domain: ${SWAGGER_EDITOR_DOMAIN}
http:
  port: ${PORT}
pg_dsn: ${PG_DSN}
